# Detector Settings
/NMS/analysis/detectorvolume HE1-He
/NMS/analysis/lostvolume PolyethyleneArea

# Source Geometry
/NMS/source/geometry/type Point
/NMS/source/geometry/centre 0 0 0

# Source Volume & Material
/NMS/source/material NMSSourceMaterial

# Cf spectrum changed (ESARDA Benchmark)
/NMS/source/cf252sfoptions 0 2











# Source Type and settings
/NMS/source/sfg false
/NMS/source/sfn true
/NMS/source/alpha false
/NMS/source/neutronAlphaN false
/NMS/source/activity 860000

# AlphaN Settings
/NMS/source/alphan/directionSampling 0
/NMS/source/alphan/energySampling 0
/NMS/source/alphan/positionSampling 0
# /NMS/source/alphan/energy   - not given
# /NMS/source/alphan/energyFilename   - not given
/NMS/source/alphan/activityCalculation 2
# /NMS/source/alphan/activity   - not given

# Runtime settings
/random/setSeeds 28607207 36633217
/NMS/run/runtime 0.5
/NMS/run/printmodulo 1000
/NMS/analysis/eventoffset 0	

# Run
/NMS/run/beamOnRuntime 1

# Create some output
/NMS/analysis/efficiency 0.31
/NMS/source/dumpstatus
/NMS/analysis/writesourceneutronenergies ep1-c2_0_0
/NMS/source/alphan/writeEnergyFile ep1-c2_0_0
/NMS/analysis/showresults
/NMS/analysis/writeincludepulsetrain true
/NMS/analysis/writeresults ep1-c2_0_0
